name       : haskell-binary-tagged
version    : '0.3'
release    : 3
source     :
    - https://hackage.haskell.org/package/binary-tagged-0.3/binary-tagged-0.3.tar.gz : 5a3f37504277cc039f9022e6a86a51a691119f673c0f31e95827f72e1be47faf
license    : BSD-3-Clause
component  : programming.haskell
summary    : Structurally tag binary serialisation stream.
description: |
    Structurally tag binary serialisation stream.
builddeps  :
    - haskell-cabal-install
    - haskell-structured-devel
rundeps    :
    - devel:
        - haskell-structured-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
