name       : haskell-binary-tagged
version    : 0.1.4.2
release    : 1
source     :
    - http://hackage.haskell.org/package/binary-tagged-0.1.4.2/binary-tagged-0.1.4.2.tar.gz : 311fab8c2bac00cb6785cb144e25ed58b2efce85e5dc64e30e2b5a2a16cdc784
license    : BSD-3-Clause
component  : programming.haskell
summary    : Structurally tag binary serialisation stream.
description: |
    Structurally tag binary serialisation stream.
builddeps  :
    - ghc
    - haskell-aeson
    - haskell-cabal-install
    - haskell-generics-sop
    - haskell-nats
    - haskell-scientific
    - haskell-semigroups
    - haskell-sha
    - haskell-text
    - haskell-vector
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
