name       : haskell-binary-tagged
version    : 0.1.5
release    : 2
source     :
    - https://hackage.haskell.org/package/binary-tagged-0.1.5/binary-tagged-0.1.5.tar.gz : d4b733a9013069f19249acad76e7f73fb41303c44dcbd2229de8d534558605e8
license    : BSD-3-Clause
component  : programming.haskell
summary    : Structurally tag binary serialisation stream.
description: |
    Structurally tag binary serialisation stream.
builddeps  :
    - ghc
    - haskell-aeson
    - haskell-base16-bytestring
    - haskell-cabal-install
    - haskell-generics-sop
    - haskell-scientific
    - haskell-sha
    - haskell-text
    - haskell-vector
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
